### ISSUE TITLE
Style the body

### ISSUE THREAD

**Issue by vasystus** [Vasystus/tic-tac-toe#3]
Style the Title or the body of the game if nessessary

**Comment by vasystus** [comment]
@sonianb  Hi Sonia. I rewrote the code, it;s working now. 
I also styled the button per request but I think I made a mistake and merged the issue myself as I couldn't add you as assignee. I raised the different issue now (Style the body or Title) - freestyle up to you, preferably still matching the button! Let's see if this time would be better?

**Comment by sonianb** [comment]
#1
